export const Experience = [
  {
    title: "Full Stack Developer",
    company: "Zaronology",
    start: new Date(2024, 6, 10),
    end: new Date(),
    description: "At Zaronology Inc. (Sparks, CA), I’m a Full-Stack Developer (07/2024–Present) delivering scalable, cost-efficient systems and user-centric features for clients such as CGC Cards, Escapology, MrBeast’s team for TeamSeas, Tax Deed Pro, and an internal blog CMS. I implemented an AWS container architecture (ECS on EC2/Fargate) that boosted application performance by 40% and reduced infrastructure costs by about $300 per month through smarter workload management. Across the stack, I built core product capabilities including a custom CMS for non-technical users, two role-based portals (Admin & Customer) with a rule builder, and a geospatial Property Auction UI with saved filters and Google Maps. I also delivered a CMS that enabled 25 non-technical users to independently manage two websites, increasing user-satisfaction scores by 15%, and optimized an existing client site to improve page-speed metrics by roughly 20% via caching and asset/code-splitting.",
    website: "https://zaronology.com/",
    skills: ["React", "NextJS", "TypeScript", "NodeJS", "Python", "AWS", "MySQL", "Strapi"],
  },
  {
    title: "Full Stack Developer",
    company: "NTx Ventures",
    start: new Date(2023, 2, 1),
    end: new Date(2024, 6, 1),
    description:
      "Develop and enhance critical components for NTx Ventures' UI and backend API using React, TypeScript, and Node.js. Collaborate with cross-functional teams to rebuild the website, including mobile UI, and optimize web scrapers utilizing AWS, improving data collection and vehicle information parsing through an Express API.",
    skills: [
      "React",
      "TypeScript",
      "Node.js",
      "AWS",
      "Express",
      "Web Scraping",
      "NestJS",
      "GraphQL",
      "MySQL",
    ],
    website: "https://www.ntx.ventures/",
  },
  {
    title: "Full Stack Developer",
    company: "ChartRequest",
    start: new Date(2022, 7, 1),
    end: new Date(2023, 2, 1),
    description:
      "Implemented and guided the development of essential components for ChartRequest using React, NextJS, TypeScript, and Ruby on Rails. Partnered with cross-functional teams to design a legal interface for medical record requests, set up automated email notifications, transition the patient portal to Stripe, and improve user security with an auto sign-out feature.",
    skills: ["React", "NextJS", "TypeScript", "Ruby on Rails", "Stripe", "PostgreSQL"],
    website: "https://chartrequest.com/",
  },
  {
    title: "Junior Full Stack Developer",
    company: "Averatist",
    start: new Date(2022, 1, 1),
    end: new Date(2022, 7, 1),
    description:
      "I worked on a team of four to develop a mobile-friendly web application aimed at helping school administration staff provide wellness resources for college students. We used React, TypeScript, MongoDB, JavaScript, Firebase, and Supabase. My daily tasks involved building applications with React components and implementing an MVP design created by the Product Owner and Designer",
    skills: ["React", "TypeScript", "MongoDB", "JavaScript", "Firebase", "Supabase"],
    website: "https://www.f6s.com/company/averatist#about",
  },
  {
    title: "Frontend Dev Instructor",
    company: "BeachCoders",
    start: new Date(2021, 7, 1),
    end: new Date(2022, 1, 1),
    description:
      "At BeachCoders, I provided one-on-one tutoring in Front-end Development, guiding students through the creation of multiple projects using JavaScript, React, NextJS, and CSS. I taught 53 unique students, focusing on JavaScript, data structures, algorithms, and the MERN stack, demonstrating a strong commitment to effective knowledge transfer.",
    skills: ["JavaScript", "React", "NextJS", "CSS", "MERN Stack"],
    website: "https://beachcoders.com/",
  },
];

export const Skills = [
  "React",
  "AWS",
  "TypeScript",
  "NextJS",
  "NestJS",
  "JavaScript",
  "Python",
  "C++/C#",
  "Java",
  "NodeJS",
  "Ruby",
  "HTML5",
  "CSS",
  "Redux",
  "Git",
  "SDLC",
  "Docker",
  "Data Structures",
  "Algorithms",
  "GraphQL",
  "SQL",
  "PostgreSQL",
  "MySQL",
  "NoSQL",
  "Collaboration",
  "Teamwork",
  "Adaptability",
];

export const Education = [
  {
    school: "Southern New Hampshire University",
    degree: "Computer Science (in progress)",
    start: new Date(2022, 1, 1),
    end: new Date(),
  },
  {
    school: "Flatiron School",
    degree: "Software Engineering",
    start: new Date(2020, 1, 1),
    end: new Date(2021, 1, 1),
  },
];
