export const PROJECTS_GETTER_KEY = "PROJECTS_BASIC_DATA";

export const CATEGORY_KEYS: { [key: string]: string } = {
  BASE: "PROJECT_CATEGORY_",
  JS: "PROJECT_CATEGORY_JS",
  REACT: "PROJECT_CATEGORY_REACT",
  PYTHON: "PROJECT_CATEGORY_PYTHON",
  C_LANG: "PROJECT_CATEGORY_C_LANG",
  API: "PROJECT_CATEGORY_API",
};
