import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div >
      <Head>
        <title>C.J Leverett</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/roboHead.png" />
      </Head>



    </div>
  )
}
