import Head from 'next/head';

export default function Home() {
	return (
		<div>
			<Head>
				<title>C.J Leverett</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/images/roboHead.png" />
			</Head>

			<div className="h-96 w-96 text-center bg-red-300">
				<button className="bg-blue-500 h-10 w-20 rounded m-3 hover:rotate-6 hover:bg-green-200">
					Click
				</button>
			</div>
		</div>
	);
}
